SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Album_Songs](
	[Album_ID] [int] NOT NULL,
	[Song_ID] [int] NOT NULL,
	[Song_Name] [varchar](20) NOT NULL,
	[Track] [int] NOT NULL,
	[Minutes] [int] NOT NULL,

 CONSTRAINT [PK_Album_Songs] PRIMARY KEY CLUSTERED 
(
	[Album_ID] ASC, [Song_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO