SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Album](
	[Album_ID] [int] NOT NULL,
	[Album_Name] [varchar](20) NOT NULL,
	[Year] [int] NULL,
	[Genre] [varchar](20) NULL,

 CONSTRAINT [PK_Album] PRIMARY KEY CLUSTERED 
(
	[Album_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO