SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Artist_Song_Collection](
	[Artist_ID] [int] NOT NULL,
	[Album_ID] [int] NOT NULL,

 CONSTRAINT [PK_Artist_Song_Collection] PRIMARY KEY CLUSTERED 
(
	[Artist_ID] ASC, [Album_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO